# Generated by Django 4.0.5 on 2022-06-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название вопроса')),
                ('text', models.CharField(max_length=1000, verbose_name='Текст вопроса')),
                ('type', models.CharField(max_length=100, verbose_name='Тип вопроса')),
                ('answer', models.CharField(max_length=100, verbose_name='Ответ на вопрос')),
                ('pool', models.CharField(max_length=100, verbose_name='Пул id')),
                ('question_id', models.CharField(max_length=100, verbose_name='Квест id')),
            ],
        ),
        migrations.CreateModel(
            name='Quest_pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пула')),
                ('role_id', models.CharField(max_length=100, verbose_name='Роль id')),
                ('quest_pool_id', models.CharField(max_length=100, verbose_name='Пул id')),
                ('slug', models.CharField(max_length=40, verbose_name='просто ид буквенное')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название роли')),
                ('webquest', models.CharField(max_length=100, verbose_name='Квест id')),
                ('role_id', models.CharField(max_length=100, verbose_name='Роль id')),
            ],
        ),
        migrations.CreateModel(
            name='WebQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название веб-квеста')),
            ],
        ),
    ]
