# Generated by Django 4.0.5 on 2022-06-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2147483640, verbose_name='текст')),
                ('slag', models.CharField(max_length=40, verbose_name='ссылка')),
            ],
        ),
    ]
