# Generated by Django 4.0.4 on 2022-05-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='value_quest',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
