# Generated by Django 4.0.4 on 2022-05-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_courses_value_quest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Курсы', 'verbose_name_plural': 'Курсы'},
        ),
    ]
