# Generated by Django 4.0.4 on 2022-05-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_courses_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='answer_to_course',
        ),
        migrations.DeleteModel(
            name='people_to_answer',
        ),
        migrations.DeleteModel(
            name='people_to_course',
        ),
        migrations.AddField(
            model_name='courses',
            name='answers',
            field=models.ManyToManyField(blank=True, to='main.answer'),
        ),
    ]
