# Generated by Django 4.0.4 on 2022-05-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_answer_to_course_delete_people_to_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='courses_for_people', to='main.answer'),
        ),
    ]
