# Generated by Django 4.0.4 on 2022-05-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_people_end_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(verbose_name='Текст задания'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='key',
            field=models.CharField(max_length=255, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='name_answer',
            field=models.CharField(max_length=255, verbose_name='Название задания'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=255, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='value_quest',
            field=models.IntegerField(verbose_name='Количество вопросов'),
        ),
    ]
