# Generated by Django 4.0.4 on 2022-05-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_answer_answer_alter_answer_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Задания', 'verbose_name_plural': 'Задания'},
        ),
    ]
