# Generated by Django 4.0.4 on 2022-05-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_answer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='value_quest',
        ),
    ]
