# Generated by Django 4.0.4 on 2022-05-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_courses_value_quest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='answers_for_courses', to='main.courses'),
        ),
    ]
