# Generated by Django 4.0.5 on 2022-06-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Рабочий день')),
            ],
            options={
                'verbose_name': 'Рабочие дни',
                'verbose_name_plural': 'Рабочие дни',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Название группы')),
                ('name_napr', models.CharField(max_length=150, verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=155, unique=True, verbose_name='ФИО')),
                ('special', models.CharField(max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
            },
        ),
        migrations.CreateModel(
            name='Raspisanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Дата')),
                ('json', models.TextField(max_length=1000, verbose_name='json')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_room', models.CharField(db_index=True, max_length=100, verbose_name='Тип аудитории')),
            ],
            options={
                'verbose_name': 'Тип кабинета',
                'verbose_name_plural': 'Типы кабинетов',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=100, verbose_name='Дисциплина')),
                ('hours', models.IntegerField(verbose_name='Часы')),
                ('hours_end', models.IntegerField(verbose_name='Прошло часов')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='all.group', verbose_name='Группа')),
                ('prepod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='all.personal', verbose_name='Преподаватель')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='all.room_type', verbose_name='Тип аудитории')),
            ],
            options={
                'verbose_name': 'Рабочая таблица',
                'verbose_name_plural': 'Рабочая таблица',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Аудитория')),
                ('type_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='all.room_type', verbose_name='Тип Аудитории')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='rukovoditel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='all.personal', verbose_name='Куратор'),
        ),
        migrations.CreateModel(
            name='Finished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(verbose_name='Часы')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='all.work', verbose_name='Дисциплина')),
            ],
        ),
        migrations.CreateModel(
            name='Closed_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата выходного')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.personal', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Метод день',
                'verbose_name_plural': 'Метод дни',
            },
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=155, unique=True, verbose_name='ФИО')),
                ('date_of_birth', models.DateField(verbose_name='ДР')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='all.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Контингент',
                'verbose_name_plural': 'Контингент',
            },
        ),
        migrations.CreateModel(
            name='Blocked_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата выходного')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Нерабочие дни группы',
                'verbose_name_plural': 'Нерабочие дни группы',
            },
        ),
    ]
